server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/railway_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Abulhasan@006}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: abulhasanrathinamohamed@gmail.com
    password: ilndssotbvbcbwmv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true